# $Id: META.yml,v 1.2 2006-06-20 12:36:11 mike Exp $

# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-Z3950-IRSpy
version:      0.01
version_from: lib/ZOOM/IRSpy.pm
installdirs:  site
requires:

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
